import chokidar from "chokidar";
import fs from "fs";
import ts from "typescript";
import path from "path";
const MODULES_DIR = path.resolve("server/modules");
const API_DIR = path.resolve("app/api");
// Parse a .route.ts file and extract route metadata
function analyzeRouteFile(filePath) {

  if (!filePath.endsWith(".route.ts")) return;

  try {
    const source = fs.readFileSync(filePath, "utf8");
   
    const sourceFile = ts.createSourceFile(filePath, source, ts.ScriptTarget.Latest, true);

    const routes = [];

    ts.forEachChild(sourceFile, (node) => {
    
      if (ts.isVariableStatement(node) && node.declarationList.declarations.length > 0) {
        
        const decl = node.declarationList.declarations[0];
        const name = decl.name.getText();
      
        if (decl.initializer && decl.initializer.getText().includes("wrapHandler")) {
          const text = decl.initializer.getText();
          
          const routeMatch = text.match(/route:\s*["'`](.*?)["'`]/);
          const methodMatch = text.match(/method:\s*["'`](.*?)["'`]/);

          if (routeMatch && methodMatch) {
            routes.push({
              exportName: name,
              route: routeMatch[1],
              method: methodMatch[1],
            });
          }
        }
      }
    });

    if (routes.length) {
      console.log(`\n🧩 Parsed route file: ${filePath}`);
      console.table(routes);

      const moduleName = path.basename(path.dirname(filePath));
      applyLogic(moduleName, routes);
    }
  } catch (err) {
    console.error("❌ Error analyzing route file:", err);
  }
}

// Generate Next.js API exports
function applyLogic(moduleName, routes) {
  const grouped = {};

 let dirToClean = path.join(API_DIR, moduleName);
if (fs.existsSync(dirToClean)) {
  fs.rmSync(dirToClean, { recursive: true, force: true });
}
  for (const route of routes) {
    
    const routePath = route.route.replace(/^\/?api\/?/, "");
    const segments = routePath.split("/").map((seg) =>
      seg.startsWith(":") ? `[${seg.slice(1)}]` : seg
    );

    const apiDir = path.join(API_DIR, ...segments);
    if (!grouped[apiDir]) grouped[apiDir] = [];
    grouped[apiDir].push(route);
  }

  for (const [apiDir, groupRoutes] of Object.entries(grouped)) {
    fs.mkdirSync(apiDir, { recursive: true });
    const apiFile = path.join(apiDir, "route.ts");

    const exports = groupRoutes.map((r) => {
      const importPath = path
        .relative(apiDir, path.join(MODULES_DIR, moduleName, `${moduleName}.route`))
        .replace(/\\/g, "/");
      const method = r.method.toUpperCase();
      const asMethod = method === "GET" && !r.exportName.startsWith("GET_") ? "GET" : method;
      return `export { ${r.exportName} as ${asMethod} } from "${importPath.startsWith(".") ? importPath : "./" + importPath}";`;
    });
     const headerComment = `/**
 * ⚠️ THIS FILE IS AUTO-GENERATED BY zyl.js WATCHER
 * Do not edit this file manually; any changes will be overwritten.
 */\n\n`;
    fs.writeFileSync(apiFile,headerComment + exports.join("\n") + "\n", "utf8");
    console.log(`✅ Updated ${path.relative(process.cwd(), apiFile)}`);
  }
}

// Watch all current and future route files recursively
function startWatcher() {

  console.log(` Watching all route files in ${MODULES_DIR}...\n`);

  chokidar
    .watch(MODULES_DIR, { persistent: true, usePolling: true, interval: 500 })
    .on("add", analyzeRouteFile)
    .on("change", analyzeRouteFile)
    .on("unlink", (filePath) => {
      // Optional: remove generated API files if route deleted
const moduleApiDir = path.join(API_DIR, moduleName);
if (fs.existsSync(moduleApiDir)) {
  fs.rmSync(moduleApiDir, { recursive: true, force: true });
}

    });
}




startWatcher();
